using System.IO;

namespace Stein.Models
{
    /// <summary>
    /// Represents a file that has been compiled by a templating engine and is ready to be rendered.
    /// </summary>
    public abstract class Template
    {
        /// <summary>
        /// Initializes a new instance of the Template class with the provided FileInfo and object.
        /// </summary>
        /// <param name="fileInfo">A FileInfo derived from the source file.</param>
        /// <param name="templateObject">Stores the object created by non-native templating engines.</param>
        public Template(FileInfo fileInfo, object templateObject) : this(fileInfo) => TemplateObject = templateObject;

        /// <summary>
        /// Initializes a new instance of the Template class with the provided FileInfo.
        /// </summary>
        /// <param name="fileInfo">A FileInfo derived from the source file.</param>
        public Template(FileInfo fileInfo) => Info = fileInfo;

        /// <summary>
        /// Contains a FileInfo object derived from the file.
        /// </summary>
        public FileInfo Info { get; }

        /// <summary>
        /// Contains an object generated by a templating engine, most often used to facilitate
        /// the rendering of the template for non-native templating engines.
        /// </summary>
        public object TemplateObject { get; }
    }
}